name: Update README

on:
  schedule:
    - cron: "0 */6 * * *"   # runs every 6 hours
  workflow_dispatch:        # lets you run manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate GitHub Stats
        run: |
          echo "Using PAT_1 token..."
        env:
          PAT_1: ${{ secrets.PAT_1 }}
